### ISSUE TITLE
Canonical URL doubles site url

### ISSUE THREAD

**Issue by iandberg** [lightspeedretail/webstore#655]
Webstores in subdirectories appear to have malformed canonical urls on category pages.
Visit a category page in a subdirectory-installed store - the canonical url appears with an extra site url like this:

http://www.mystore.com/store/http://www.mystore.com/store/shirts

webstore 3.2.6

**Comment by euoia** [comment]
Hi @iandberg,

This should have been fixed in 3.2.6 but requires you to go into admin panel and disable "Use Categories In Product Urls", save, then re-enable "Use Categories In Product Urls" and save again. See the release notes here:
http://www.lightspeedpos.com/release-notes/webstore/

Please let me know how you get on.

**Comment by iandberg** [comment]
Thanks for the reply.
Many of our clients haven't turned the 'Use Categories In Product Urls' feature on to begin with. I picked a sample client, turned ON 'Use Categories In Product Urls' - canonical url still the same 'doubled' state. So with ''Use Categories In Product Urls'' either off or on, I still see the doubled state.

**Comment by euoia** [comment]
Hi @iandberg - we just tested this and can't reproduce on Web Store 3.2.6.

Where are you seeing the canonical URL? Can you provide an example URL where I can see the problem?

If you are able to check the database, look in {{xlsws_category.request_url}}. If you see full URLs in this column (e.g. http://www.mystore.com/store/shirts) and not just the path (e.g. /shirts) then the you can fix this on Web Store 3.2.6 by toggling the "Use Categories In Product Urls" as mentioned before.

**Comment by iandberg** [comment]
Hi,
The canonical url I'm seeing is in the <head> here:
<link rel="canonical" href="<?= $this->CanonicalUrl; ?>"/>
The category urls look fine in the db, there's no extra stuff there, just the path. The doubling up seems to happen on category pages only. It also may be a store-in-subdirectory thing. I checked a client with 3.2.6 with store in the root, and the can. url is fine.
![canonical](https://cloud.githubusercontent.com/assets/583913/7437151/fe8508f2-f009-11e4-84b7-4ae3626db14d.png)
Thanks!

**Comment by gabeguz** [comment]
Very strange, I've tried to replicate your setup on my dev environment, and I can't reproduce the issue.  Is there any more data you can provide that will help us reproduce the issue?  

Here is what category canonical urls look like for me, with web store installed in a sub folder: 

![screen shot 2015-05-04 at 10 00 59 am](https://cloud.githubusercontent.com/assets/132174/7454755/ceb83bf2-f244-11e4-86be-0a9d931bde81.png)

Have you customized any view files or controllers?  Is it possible that a needed change to some of the files hasn't made it over into your code?

**Comment by iandberg** [comment]
Thanks for looking into it. I found that it's our code (big surprise). Sorry to use up your time.
